# Site setings
name: 'Ahmed Abdelmaaboud'
description: 'Application Security / Offensive Security'
meta_description: ''
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is Charles Lavoie. I'm a freelance web developer, author and speaker based in Montreal, Canada. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://offensiveforce.com
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: ahmed.elhady.mohamed@gmail.com
contact_page_description: "Protect your systems with expert offensive security services. Specializing in penetration testing, vulnerability assessments, and red teaming, I proactively identify and mitigate threats. Reach out today to fortify your defenses!"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'kingasmk'
facebook: 'kingasmk'
github: 'ahmed.elhady.mohamed'
medium: '@kingasmk'
instagram: 'kingasmk'
linkedin: 'ahmed elhady mohamed'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
