# Site setings
name: 'Ahmed Abdelmaaboud | OffensiveForce'
description: 'Application Security | Offensive Security'
meta_description: ''
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is Ahmed Abdelmaaboud. I'm an Application Security / Offensive Security based in Amsterdam, Netherlands. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://offensiveforce.com
disqus: 'OffensiveForce'
mailchimp_url: 'https://offensiveforce.us12.list-manage.com/subscribe/post?u=2acb09bfaaf6bfaf171b87e58&amp;id=0b716de6a8&amp;f_id=00e88de1f0'
# Add your GA Tracking Id Todo
ga_analytics: 

# Contact form setings
email: ahmed.elhady.mohamed@gmail.com
contact_page_description: "Protect your systems with expert offensive security services. Specializing in penetration testing, vulnerability assessments, and red teaming, I proactively identify and mitigate threats. Reach out today to fortify your defenses!"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'kingasmk'
facebook: 'kingasmk'
github: 'ahmed.elhady.mohamed'
medium: '@ahmed_elhady'
instagram: 'kingasmk'
linkedin: 'ahmed elhady mohamed'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
